### ISSUE TITLE
Google Analytics tracking on Find not working.

### ISSUE THREAD

**Issue by sengi** [alphagov/govuk-dgu-charts#128]
Last data is from 2023-11-28, before it moved from PaaS to k8s.

Looks like it's not configured; there's no mention of [GA_TRACKING_ID](https://github.com/alphagov/datagovuk_find/blob/49d7735/config/application.rb#L56) in this repo.

**Comment by sengi** [comment]
@nicholsj is gonna find someone who has access to the data.gov.uk web property in Analytics so we can find out the tag ID.

**Comment by nicholsj** [comment]
ID was apparently `UA-10855508-1`

**Comment by sengi** [comment]
Oh deary me. Turns out that GA_TRACKING_ID environment variable is only read at build-time 🤡

**Comment by sengi** [comment]
So it's easy enough to work around it by setting it at build time, as long as we don't care about it varying by environment. Which we probably don't, cos the environments have different domains anyway.

**Comment by sengi** [comment]
Let's make the environment variable work for now. Still gonna need updating to gtag.js or Tag Manager at some point.
